void die(char *str);
int test(comm comm);
int testmain(char **argv);
int testexpr(void);
int testexpr2(void);
int testexpr3(void);
int testexpr4(void);
int doaccess(int c);
struct stat *getstat(void);
unsigned short dostat(void);
